### ISSUE TITLE
depth image units and scaling factor

### ISSUE THREAD

**Issue by sanjaysswami** [zhujiangchao/realsense_camera#1]
@zhujiangchao can you please tell me what are the units for depth images? in meter or milimeter?
I have used your package to capture images (used aligned depth). when I checked the values of depth images, i got couple of values. For an example for one image maximum value was 14 and minimum was 0.

Another question is, while ros node depth stream was running, I noticed z16 in curly brackets. Then I found the meaning of z16 [here](https://software.intel.com/sites/products/realsense/camera/namespacers.html#a447cba2f10f1dc5aac305658756c238babf73b5318257eb20d832e72af8b83eca). Can you please tell me what depth scale you have used?

**Comment by zhujiangchao** [comment]
@sanjaysswami the units for the depth image are in meter. and the depth scale can be got by using the following function get_depth_scale(), you can go for this link  for more details of the usage of this function.(https://github.com/IntelRealSense/librealsense/issues/2348)

**Comment by sanjaysswami** [comment]
@zhujiangchao Thank you very much for the help.
